/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petsystem;

import java.sql.*;
import java.util.*;




/**
 *
 * 
 */
public class Lost_information extends javax.swing.JFrame {
    
    static public Lost_information lost_information;

    /**
     
     */
    public Lost_information() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_sex = new javax.swing.JComboBox<>();
        jButton_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_breed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_microchip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2_bodycolor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3_eyecolor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser_date = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_discription = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jTextField_location = new javax.swing.JTextField();
        jTextField4_petname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_age = new javax.swing.JTextField();
        jButton_Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost Information");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("*Pet Type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jComboBox_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat", "Bird", "Other" }));
        jPanel1.add(jComboBox_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 217, -1));

        jLabel6.setText("Pet Sex");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jComboBox_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", " " }));
        jPanel1.add(jComboBox_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 180, 30));

        jButton_logout.setText("Log Out");
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 40));

        jLabel2.setText("*Pet Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 79, -1));
        jPanel1.add(jTextField1_breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, -1));

        jLabel7.setText("Micro Chip");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jTextField_microchip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_microchipActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_microchip, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 170, -1));

        jLabel3.setText("*Pet Breed");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        jPanel1.add(jTextField2_bodycolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 210, -1));

        jLabel4.setText("Eye Color");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 20));

        jLabel5.setText("Body Color");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jTextField3_eyecolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_eyecolorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3_eyecolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 210, -1));

        jLabel8.setText("*Lost Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jDateChooser_date.setDateFormatString("yyyy,MM,dd");
        jPanel1.add(jDateChooser_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 190, -1));

        jLabel10.setText("*Lost Location");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        jTextArea_discription.setColumns(20);
        jTextArea_discription.setRows(5);
        jScrollPane1.setViewportView(jTextArea_discription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 180, 140));

        jLabel11.setText("Discription");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));
        jPanel1.add(jTextField_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 290, 190, -1));
        jPanel1.add(jTextField4_petname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 210, -1));

        jLabel9.setText("Pet Age");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 62, -1));

        jTextField_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ageActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 210, -1));

        jButton_Submit.setText("Submit");
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3_eyecolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_eyecolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_eyecolorActionPerformed

    private void jTextField_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ageActionPerformed

    private void jTextField_microchipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_microchipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_microchipActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed

        String ptype=jComboBox_type.getSelectedItem().toString();
        String pname=jTextField4_petname.getText();
	String pbreed=jTextField1_breed.getText();
        String pbcolor=jTextField2_bodycolor.getText();
        String pecolor=jTextField3_eyecolor.getText();
	String age=jTextField_age.getText();
	String llocation=jTextField_location.getText();
        String psex=jComboBox_sex.getSelectedItem().toString();
        String mchip=jTextField_microchip.getText();
	java.util.Date lostdate=jDateChooser_date.getDate();
	String llostdate = String.format("%1$ty-%1$tm-%1$td", lostdate); 
        String discription=jTextArea_discription.getText();
        String currentUserId = CurrentUser.CurrentUserId;
				
	


   
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lost_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lost_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lost_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lost_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lost_information=new Lost_information();
                lost_information.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JComboBox<String> jComboBox_sex;
    private javax.swing.JComboBox<String> jComboBox_type;
    private com.toedter.calendar.JDateChooser jDateChooser_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_discription;
    private javax.swing.JTextField jTextField1_breed;
    private javax.swing.JTextField jTextField2_bodycolor;
    private javax.swing.JTextField jTextField3_eyecolor;
    private javax.swing.JTextField jTextField4_petname;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_location;
    private javax.swing.JTextField jTextField_microchip;
    // End of variables declaration//GEN-END:variables
}
