/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petsystem;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author xumin c
 */
public class MyAccount extends javax.swing.JFrame {

    /**
     * Creates new form MyAccount
     */
    public MyAccount() {
        initComponents();
        DeletereportList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jButton_Update = new javax.swing.JButton();
        jButton_Mainpage = new javax.swing.JButton();
        Button_Logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Delete = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 500));
        setPreferredSize(new java.awt.Dimension(850, 500));
        setSize(new java.awt.Dimension(850, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 137, -1, -1));

        jLabel5.setText("email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 238, -1, -1));
        getContentPane().add(jTextField_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 137, 212, -1));
        getContentPane().add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 233, 212, -1));

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jButton_Mainpage.setText("Main Page");
        jButton_Mainpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MainpageActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Mainpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 6, -1, -1));

        Button_Logout.setText("Log Out");
        Button_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 6, -1, -1));

        jButton1.setText("Delete Your Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        table_Delete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Report ID", "Report Date", "Status", "Pet Type", "Pet name", "Pet breed"
            }
        ));
        table_Delete.getTableHeader().setReorderingAllowed(false);
        table_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DeleteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Delete);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 137, 450, 122));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        
        String email=jTextField_email.getText();
        String phone=jTextField_phone.getText();
        String currentUserId = CurrentUser.CurrentUserId;
        try {
		Connection conn = MyConnection.GetConnection();
				
				
                 PreparedStatement ps = conn.prepareStatement("UPDATE USER SET email=?,phone_number=? WHERE user_id=?");

                                 //ps.setString(1, "1");
                                 ps.setString(1, email);
                                 ps.setString(2, phone);
                                 ps.setString(3,currentUserId);
                                 ps.execute();
                                 
                                 JOptionPane.showMessageDialog(null, "Update Successful !");
                                 jTextField_phone.setText(null);
                                 jTextField_email.setText(null);
    }//GEN-LAST:event_jButton_UpdateActionPerformed
catch (SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					         }
        
    }
    
    
    private void jButton_MainpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MainpageActionPerformed
        
        
        AfterLogin afterLogin=new AfterLogin();
                    afterLogin.setVisible(true);
                    dispose();
    }//GEN-LAST:event_jButton_MainpageActionPerformed

    private void Button_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LogoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_Button_LogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = table_Delete.getSelectedRow();
        int selectedColumn = 0;
        
        String lf_id = table_Delete.getValueAt(selectedRow, selectedColumn).toString();
        
        try {
            PreparedStatement ps = MyConnection.GetConnection().prepareStatement("DELETE FROM LOSTFOUND WHERE lf_id=?;");
            ps.setString(1,lf_id);
            int deletedCount = ps.executeUpdate();
            if(deletedCount>0){
                JOptionPane.showMessageDialog(null, "Delete Successful !");// success
            }
            
            DeletereportList();
        }
        catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
	}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        
        
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void table_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DeleteMouseClicked
        // TODO add your handling code here:
        
        //"DELETE FROM LOSTFOUND L WHERE L.lf_id=?;"
        
        
    }//GEN-LAST:event_table_DeleteMouseClicked
     
    public void DeletereportList()
    {
        String currentUserId = CurrentUser.CurrentUserId;
        try {
            
            ArrayList<DeleteReport> deleteReportList = new ArrayList<DeleteReport>();
            PreparedStatement ps = MyConnection.GetConnection().prepareStatement("SELECT L.lf_id,PI.create_date,L.status_flag,P.pet_type,P.pet_name,P.pet_breed FROM LOSTFOUND L,PUT_INFORMATION PI ,PET P,USER U WHERE L.lf_id=PI.lf_id AND PI.user_id=U.user_id AND P.pet_lfid=L.lf_id AND PI.user_id=? ");
            
            ps.setString(1,currentUserId);
            
            ResultSet rs = ps.executeQuery();
						
            while( rs.next() ){
                int report_id=rs.getInt(1);
                String report_date = rs.getString(2);
                String status_flag=rs.getString(3);
                String pet_type=rs.getString(4);
                String pet_name=rs.getString(5);
                String pet_breed=rs.getString(6);
                
                
                DeleteReport deleteReport = new DeleteReport(report_id,report_date,status_flag,pet_type,pet_name,pet_breed);
                deleteReportList.add(deleteReport);
            }
            
            DefaultTableModel dtm = (DefaultTableModel)table_Delete.getModel();
            dtm.setRowCount(0);
            
            
            for( int i=0, n=deleteReportList.size(); i<n; i++){
                Object[] row = new Object[6];
                row[0]=deleteReportList.get(i).getreportid();
                row[1] = deleteReportList.get(i).getreportdate();
                row[2] = deleteReportList.get(i).getstatusflag();
                row[3] = deleteReportList.get(i).getpettype();
                row[4] = deleteReportList.get(i).getpetname();
                row[5] = deleteReportList.get(i).getpetbreed();
                
                dtm.addRow(row);
            }
            
            
        
            //st=MyConnection.createStatement();
            //rs=st.executeQuery(ps);
            
            
            
        
        
        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
	}
        
    }
    
                                          
        
        
    
    
        
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Logout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Mainpage;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTable table_Delete;
    // End of variables declaration//GEN-END:variables
}
